// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/domain/models/proto/shortener.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ShortenURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortenURLResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetOriginalURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortId       string                 `protobuf:"bytes,1,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLRequest) Reset() {
	*x = GetOriginalURLRequest{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLRequest) ProtoMessage() {}

func (x *GetOriginalURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalURLRequest) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

type GetOriginalURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,2,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLResponse) Reset() {
	*x = GetOriginalURLResponse{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLResponse) ProtoMessage() {}

func (x *GetOriginalURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GetOriginalURLResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *GetOriginalURLResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type BatchRequestEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequestEntity) Reset() {
	*x = BatchRequestEntity{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequestEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequestEntity) ProtoMessage() {}

func (x *BatchRequestEntity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequestEntity.ProtoReflect.Descriptor instead.
func (*BatchRequestEntity) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *BatchRequestEntity) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchRequestEntity) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type APIShortenBatchURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*BatchRequestEntity  `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIShortenBatchURLRequest) Reset() {
	*x = APIShortenBatchURLRequest{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIShortenBatchURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIShortenBatchURLRequest) ProtoMessage() {}

func (x *APIShortenBatchURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIShortenBatchURLRequest.ProtoReflect.Descriptor instead.
func (*APIShortenBatchURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *APIShortenBatchURLRequest) GetUrls() []*BatchRequestEntity {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *APIShortenBatchURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BatchResponseEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponseEntity) Reset() {
	*x = BatchResponseEntity{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponseEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponseEntity) ProtoMessage() {}

func (x *BatchResponseEntity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponseEntity.ProtoReflect.Descriptor instead.
func (*BatchResponseEntity) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *BatchResponseEntity) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchResponseEntity) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type APIShortenBatchURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchResponseEntity `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIShortenBatchURLResponse) Reset() {
	*x = APIShortenBatchURLResponse{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIShortenBatchURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIShortenBatchURLResponse) ProtoMessage() {}

func (x *APIShortenBatchURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIShortenBatchURLResponse.ProtoReflect.Descriptor instead.
func (*APIShortenBatchURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *APIShortenBatchURLResponse) GetResults() []*BatchResponseEntity {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *APIShortenBatchURLResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type APIGetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIGetUserURLsRequest) Reset() {
	*x = APIGetUserURLsRequest{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetUserURLsRequest) ProtoMessage() {}

func (x *APIGetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*APIGetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *APIGetUserURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURL) Reset() {
	*x = UserURL{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURL) ProtoMessage() {}

func (x *UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURL.ProtoReflect.Descriptor instead.
func (*UserURL) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *UserURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type APIGetUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserURL             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIGetUserURLsResponse) Reset() {
	*x = APIGetUserURLsResponse{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetUserURLsResponse) ProtoMessage() {}

func (x *APIGetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*APIGetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *APIGetUserURLsResponse) GetUrls() []*UserURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *APIGetUserURLsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *APIGetUserURLsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UrlIds        []string               `protobuf:"bytes,2,rep,name=url_ids,json=urlIds,proto3" json:"url_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserURLsRequest) GetUrlIds() []string {
	if x != nil {
		return x.UrlIds
	}
	return nil
}

type DeleteUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsResponse) Reset() {
	*x = DeleteUserURLsResponse{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsResponse) ProtoMessage() {}

func (x *DeleteUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserURLsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteUserURLsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{13}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *PingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIp      string                 `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsRequest) Reset() {
	*x = StatisticsRequest{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsRequest) ProtoMessage() {}

func (x *StatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsRequest.ProtoReflect.Descriptor instead.
func (*StatisticsRequest) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{15}
}

func (x *StatisticsRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type StatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsersCount    int64                  `protobuf:"varint,1,opt,name=users_count,json=usersCount,proto3" json:"users_count,omitempty"`
	UrlsCount     int64                  `protobuf:"varint,2,opt,name=urls_count,json=urlsCount,proto3" json:"urls_count,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsResponse) Reset() {
	*x = StatisticsResponse{}
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsResponse) ProtoMessage() {}

func (x *StatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_models_proto_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsResponse.ProtoReflect.Descriptor instead.
func (*StatisticsResponse) Descriptor() ([]byte, []int) {
	return file_internal_domain_models_proto_shortener_proto_rawDescGZIP(), []int{16}
}

func (x *StatisticsResponse) GetUsersCount() int64 {
	if x != nil {
		return x.UsersCount
	}
	return 0
}

func (x *StatisticsResponse) GetUrlsCount() int64 {
	if x != nil {
		return x.UrlsCount
	}
	return 0
}

func (x *StatisticsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_internal_domain_models_proto_shortener_proto protoreflect.FileDescriptor

const file_internal_domain_models_proto_shortener_proto_rawDesc = "" +
	"\n" +
	",internal/domain/models/proto/shortener.proto\x12\tshortener\"O\n" +
	"\x11ShortenURLRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"V\n" +
	"\x12ShortenURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"2\n" +
	"\x15GetOriginalURLRequest\x12\x19\n" +
	"\bshort_id\x18\x01 \x01(\tR\ashortId\"\x7f\n" +
	"\x16GetOriginalURLResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x02 \x01(\bR\tisDeleted\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"^\n" +
	"\x12BatchRequestEntity\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"g\n" +
	"\x19APIShortenBatchURLRequest\x121\n" +
	"\x04urls\x18\x01 \x03(\v2\x1d.shortener.BatchRequestEntityR\x04urls\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"Y\n" +
	"\x13BatchResponseEntity\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"{\n" +
	"\x1aAPIShortenBatchURLResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.shortener.BatchResponseEntityR\aresults\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"0\n" +
	"\x15APIGetUserURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"I\n" +
	"\aUserURL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"}\n" +
	"\x16APIGetUserURLsResponse\x12&\n" +
	"\x04urls\x18\x01 \x03(\v2\x12.shortener.UserURLR\x04urls\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"I\n" +
	"\x15DeleteUserURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aurl_ids\x18\x02 \x03(\tR\x06urlIds\"W\n" +
	"\x16DeleteUserURLsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\r\n" +
	"\vPingRequest\"M\n" +
	"\fPingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"0\n" +
	"\x11StatisticsRequest\x12\x1b\n" +
	"\tclient_ip\x18\x01 \x01(\tR\bclientIp\"y\n" +
	"\x12StatisticsResponse\x12\x1f\n" +
	"\vusers_count\x18\x01 \x01(\x03R\n" +
	"usersCount\x12\x1d\n" +
	"\n" +
	"urls_count\x18\x02 \x01(\x03R\turlsCount\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\x93\x05\n" +
	"\fURLShortener\x12I\n" +
	"\n" +
	"ShortenURL\x12\x1c.shortener.ShortenURLRequest\x1a\x1d.shortener.ShortenURLResponse\x12U\n" +
	"\x0eGetOriginalURL\x12 .shortener.GetOriginalURLRequest\x1a!.shortener.GetOriginalURLResponse\x12L\n" +
	"\rAPIShortenURL\x12\x1c.shortener.ShortenURLRequest\x1a\x1d.shortener.ShortenURLResponse\x12a\n" +
	"\x12APIShortenBatchURL\x12$.shortener.APIShortenBatchURLRequest\x1a%.shortener.APIShortenBatchURLResponse\x12U\n" +
	"\x0eAPIGetUserURLs\x12 .shortener.APIGetUserURLsRequest\x1a!.shortener.APIGetUserURLsResponse\x12U\n" +
	"\x0eDeleteUserURLs\x12 .shortener.DeleteUserURLsRequest\x1a!.shortener.DeleteUserURLsResponse\x127\n" +
	"\x04Ping\x12\x16.shortener.PingRequest\x1a\x17.shortener.PingResponse\x12I\n" +
	"\n" +
	"Statistics\x12\x1c.shortener.StatisticsRequest\x1a\x1d.shortener.StatisticsResponseB\x0fZ\rinternal/grpcb\x06proto3"

var (
	file_internal_domain_models_proto_shortener_proto_rawDescOnce sync.Once
	file_internal_domain_models_proto_shortener_proto_rawDescData []byte
)

func file_internal_domain_models_proto_shortener_proto_rawDescGZIP() []byte {
	file_internal_domain_models_proto_shortener_proto_rawDescOnce.Do(func() {
		file_internal_domain_models_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_domain_models_proto_shortener_proto_rawDesc), len(file_internal_domain_models_proto_shortener_proto_rawDesc)))
	})
	return file_internal_domain_models_proto_shortener_proto_rawDescData
}

var file_internal_domain_models_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_domain_models_proto_shortener_proto_goTypes = []any{
	(*ShortenURLRequest)(nil),          // 0: shortener.ShortenURLRequest
	(*ShortenURLResponse)(nil),         // 1: shortener.ShortenURLResponse
	(*GetOriginalURLRequest)(nil),      // 2: shortener.GetOriginalURLRequest
	(*GetOriginalURLResponse)(nil),     // 3: shortener.GetOriginalURLResponse
	(*BatchRequestEntity)(nil),         // 4: shortener.BatchRequestEntity
	(*APIShortenBatchURLRequest)(nil),  // 5: shortener.APIShortenBatchURLRequest
	(*BatchResponseEntity)(nil),        // 6: shortener.BatchResponseEntity
	(*APIShortenBatchURLResponse)(nil), // 7: shortener.APIShortenBatchURLResponse
	(*APIGetUserURLsRequest)(nil),      // 8: shortener.APIGetUserURLsRequest
	(*UserURL)(nil),                    // 9: shortener.UserURL
	(*APIGetUserURLsResponse)(nil),     // 10: shortener.APIGetUserURLsResponse
	(*DeleteUserURLsRequest)(nil),      // 11: shortener.DeleteUserURLsRequest
	(*DeleteUserURLsResponse)(nil),     // 12: shortener.DeleteUserURLsResponse
	(*PingRequest)(nil),                // 13: shortener.PingRequest
	(*PingResponse)(nil),               // 14: shortener.PingResponse
	(*StatisticsRequest)(nil),          // 15: shortener.StatisticsRequest
	(*StatisticsResponse)(nil),         // 16: shortener.StatisticsResponse
}
var file_internal_domain_models_proto_shortener_proto_depIdxs = []int32{
	4,  // 0: shortener.APIShortenBatchURLRequest.urls:type_name -> shortener.BatchRequestEntity
	6,  // 1: shortener.APIShortenBatchURLResponse.results:type_name -> shortener.BatchResponseEntity
	9,  // 2: shortener.APIGetUserURLsResponse.urls:type_name -> shortener.UserURL
	0,  // 3: shortener.URLShortener.ShortenURL:input_type -> shortener.ShortenURLRequest
	2,  // 4: shortener.URLShortener.GetOriginalURL:input_type -> shortener.GetOriginalURLRequest
	0,  // 5: shortener.URLShortener.APIShortenURL:input_type -> shortener.ShortenURLRequest
	5,  // 6: shortener.URLShortener.APIShortenBatchURL:input_type -> shortener.APIShortenBatchURLRequest
	8,  // 7: shortener.URLShortener.APIGetUserURLs:input_type -> shortener.APIGetUserURLsRequest
	11, // 8: shortener.URLShortener.DeleteUserURLs:input_type -> shortener.DeleteUserURLsRequest
	13, // 9: shortener.URLShortener.Ping:input_type -> shortener.PingRequest
	15, // 10: shortener.URLShortener.Statistics:input_type -> shortener.StatisticsRequest
	1,  // 11: shortener.URLShortener.ShortenURL:output_type -> shortener.ShortenURLResponse
	3,  // 12: shortener.URLShortener.GetOriginalURL:output_type -> shortener.GetOriginalURLResponse
	1,  // 13: shortener.URLShortener.APIShortenURL:output_type -> shortener.ShortenURLResponse
	7,  // 14: shortener.URLShortener.APIShortenBatchURL:output_type -> shortener.APIShortenBatchURLResponse
	10, // 15: shortener.URLShortener.APIGetUserURLs:output_type -> shortener.APIGetUserURLsResponse
	12, // 16: shortener.URLShortener.DeleteUserURLs:output_type -> shortener.DeleteUserURLsResponse
	14, // 17: shortener.URLShortener.Ping:output_type -> shortener.PingResponse
	16, // 18: shortener.URLShortener.Statistics:output_type -> shortener.StatisticsResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_domain_models_proto_shortener_proto_init() }
func file_internal_domain_models_proto_shortener_proto_init() {
	if File_internal_domain_models_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_domain_models_proto_shortener_proto_rawDesc), len(file_internal_domain_models_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_domain_models_proto_shortener_proto_goTypes,
		DependencyIndexes: file_internal_domain_models_proto_shortener_proto_depIdxs,
		MessageInfos:      file_internal_domain_models_proto_shortener_proto_msgTypes,
	}.Build()
	File_internal_domain_models_proto_shortener_proto = out.File
	file_internal_domain_models_proto_shortener_proto_goTypes = nil
	file_internal_domain_models_proto_shortener_proto_depIdxs = nil
}
